services:

  gateway:
    build: ./gateway
    ports:
      - "8005:8005"
    container_name: gateway
    environment:
      - AUTH_SVC_ADDRESS=${AUTH_SVC_ADDRESS}
      - CRUDOP_URL=${CRUDOP_URL}
    depends_on:
      - auth
      - crudop

  auth:
    build: ./auth
    ports:
      - "5000:5000"
    container_name: auth
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  crudop:
    build: ./crudop
    ports:
      - "5002:5002"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_CRUD_USER}
      - MYSQL_PASSWORD=${MYSQL_CRUD_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_CRUD_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
