services:

  frontapp:
    build: ./frontapp
    ports:
      - "8005:80"
    container_name: frontapp
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    container_name: gateway
    environment:
      - AUTH_SVC_ADDRESS=${AUTH_SVC_ADDRESS}
    depends_on:
      - auth

  auth:
    build: ./auth
    ports:
      - "5000:5000"
    container_name: auth
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: