version: "3.9"

services:
  auth:
    build: .
    ports:
      - "5000:5000"
    container_name: auth
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=auth_user
      - MYSQL_PASSWORD=auth123
      - MYSQL_DB=auth
      - MYSQL_PORT=3306
      - JWT_SECRET=supersecretkey
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: